const createCrudEndpoints = (base: string) => ({
  list: base,
  create: base,
  detail: (id: string) => `${base}/id/${id}`,
  update: (id: string) => `${base}/id/${id}`,
  delete: (id: string) => `${base}/id/${id}`,
});

export const endpoints = {
  user: createCrudEndpoints("/user"),
  student: createCrudEndpoints("/student"),
  faculty: createCrudEndpoints("/faculty"),
  exam: createCrudEndpoints("/exam"),
  course: createCrudEndpoints("/course"),
  material: createCrudEndpoints("/material"),
  category: createCrudEndpoints("/category"),
  subCategory: createCrudEndpoints("/sub-category"),
  article: createCrudEndpoints("/article"),
  blog: createCrudEndpoints("/blog"),
  language: createCrudEndpoints("/language"),
  tag: createCrudEndpoints("/tag"),
  quiz: createCrudEndpoints("/quiz"),
  subject: createCrudEndpoints("/subject"),
  pyq: createCrudEndpoints("/pyq"),
  mcq: createCrudEndpoints("/mcq"),
  homeCarousel: createCrudEndpoints("/home-carousel"),
  whyChooseUs: createCrudEndpoints("/why-choose-us"),
  whatsNew: createCrudEndpoints("/whats-new"),
  testimonial: createCrudEndpoints("/testimonial"),
  faq: createCrudEndpoints("/faq"),
  aboutUs: createCrudEndpoints("/about-us"),
  getInTouch: createCrudEndpoints("/get-in-touch"),
  termsAndConditions: createCrudEndpoints("/terms-and-conditions"),
  privacyPolicy: createCrudEndpoints("/privacy-policy"),
  socials: createCrudEndpoints("/socials"),
  metaData: createCrudEndpoints("/meta-data"),
  contact: createCrudEndpoints("/contact"),
};
